package com.project.board0905.domain.admin.entity;

public enum AdminActionType {
    USER_ROLE_UPDATE, USER_STATUS_UPDATE, USER_PASSWORD_RESET,
    BOARD_UPDATE, BOARD_DELETE_SOFT, BOARD_RESTORE, BOARD_NOTICE_TOGGLE,
    CATEGORY_UPDATE, CATEGORY_DELETE,
    STAT_EXPORT
}
